### ISSUE TITLE
Dropdown doesn't respect color theme

### ISSUE THREAD

**Issue by tblanarik** [mimamercury/mimamercury.com#5]
Hey there! Encountered a very small UI bug. Sadly, I'm not much of a front-end guy, so I'm not likely to have a PR for you on this one 😅.

Repro:
1. In Microsoft Edge 121.0.2277.4 (but likely any Chrome-based browser)
2. Visit: `https://mimamercury.com/food-inspections`
3. Set color theme to `dark mode`
4. Select the dropdown to change how many entries are shown
5. See that it is white text on a white background (screenshot below)

![a dropdown with white text on a white background which is not readable](https://github.com/mimamercury/mimamercury.com/assets/1554630/327f4a89-7094-444a-b007-c42e3ef9750b)

PS: thanks for making this! It's great!

**Comment by sethvincent** [comment]
Thanks for opening this! I'll check it out.

**Comment by sethvincent** [comment]
Tried to reproduce but didn't see it on macos. I'll have to get out the windows machine soon and take a look.

**Comment by tblanarik** [comment]
Gimme an @ if you need me to try anything (debug or running a branch locally or something)
